on:
  push:
    branches:
      - master
name: Deploy Production
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
      BOT_NAME: ${{ secrets.BOT_NAME }}
      REGION: ${{ secrets.REGION }}
      POSTS_TABLE_NAME: ${{ secrets.POSTS_TABLE_NAME }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
    - uses: actions/checkout@v2

    - name: Debug env
      run: node scripts/debug/index.js

    - name: Install Modules
      run: npm ci

    - name: Test
      run: npm run test

    - name: Build 
      run: npm run build

    - name: Serverless Deploy 
      uses: serverless/github-action@master
      with:
        args: deploy --env=production --region=eu-west-1
      env:
        NODE_ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
